export { default as About } from './about'
export { default as Contact } from './contact'
export { default as Home } from './home'
export { default as Layout } from './layout'
export { default as Timeline } from './timeline'
